# Generated by Django 2.2.24 on 2022-03-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0004_theme_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=models.TextField(blank=True, help_text='Upload Link your Logo', verbose_name='Logo'),
        ),
    ]
