# Generated by Django 2.2.24 on 2022-03-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0005_auto_20220304_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
