# Generated by Django 2.2.24 on 2022-03-04 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0006_auto_20220304_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='logo',
        ),
    ]
