# Generated by Django 2.2.24 on 2022-03-04 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0007_remove_theme_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='logo',
            field=models.TextField(blank=True, help_text='URL your Logo', verbose_name='Logo'),
        ),
    ]
