# Generated by Django 2.2.24 on 2022-03-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0008_theme_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='logofile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
