# Generated by Django 2.2.24 on 2022-03-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0011_auto_20220305_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='fontlink',
            field=models.TextField(blank=True, help_text='Link google font '),
        ),
    ]
