# Generated by Django 2.2.24 on 2022-03-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0012_theme_fontlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='fontlink',
        ),
        migrations.AddField(
            model_name='theme',
            name='fontname',
            field=models.CharField(blank=True, help_text='Name google font (no spaces):  ', max_length=128, verbose_name='Fontname'),
        ),
    ]
