# Generated by Django 2.2.24 on 2022-03-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0013_auto_20220305_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='fontfile',
            field=models.ImageField(blank=True, null=True, upload_to='static/appearance/fonts'),
        ),
    ]
