# Generated by Django 2.2.24 on 2022-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0014_theme_fontfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='fontfile',
            field=models.FileField(blank=True, null=True, upload_to='static/appearance/fonts'),
        ),
    ]
