# Generated by Django 2.2.24 on 2022-03-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0015_auto_20220305_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='fontselect',
            field=models.CharField(choices=[('', '--'), ('link', 'Link'), ('file', 'File')], default='', max_length=4),
        ),
        migrations.AddField(
            model_name='theme',
            name='logoselect',
            field=models.CharField(choices=[('', '--'), ('link', 'Link'), ('file', 'File')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='theme',
            name='fontname',
            field=models.CharField(blank=True, help_text='Input name google font (no spaces)  ', max_length=128, verbose_name='Fontname'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='label',
            field=models.CharField(db_index=True, help_text='A short text describing the theme.If the Label is set to "ThemeCS", the created theme will be the Defalut theme of the website.', max_length=128, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=models.TextField(blank=True, help_text='Input URL your Logo', verbose_name='Logo'),
        ),
    ]
