# Generated by Django 2.2.24 on 2022-03-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0016_auto_20220306_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='fontselect',
            field=models.CharField(choices=[('N', '------'), ('L', 'Link'), ('F', 'File')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logoselect',
            field=models.CharField(choices=[('N', '------'), ('L', 'Link'), ('F', 'File')], default='N', max_length=1),
        ),
    ]
