# Generated by Django 2.2.24 on 2022-03-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0017_auto_20220306_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='fontselect',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='logoselect',
        ),
    ]
