# Generated by Django 2.2.24 on 2022-03-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0018_auto_20220306_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='label',
            field=models.CharField(db_index=True, help_text='A short text describing the theme.If the Label is set to "ThemeCP", the created theme will be the Defalut theme of the website.', max_length=128, unique=True, verbose_name='Label'),
        ),
    ]
