# Generated by Django 2.2.24 on 2022-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0019_auto_20220306_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='defaulttheme',
            field=models.BooleanField(default=True),
        ),
    ]
