# Generated by Django 2.2.24 on 2022-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0020_theme_defaulttheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='defaulttheme',
            field=models.BooleanField(default=True, verbose_name='Use to default Theme '),
        ),
    ]
