# Generated by Django 2.2.24 on 2022-03-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0022_auto_20220317_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ('label',), 'verbose_name': 'Theme', 'verbose_name_plural': 'Themess'},
        ),
    ]
