# Generated by Django 2.2.24 on 2022-03-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0024_auto_20220317_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='fontfile',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='logofile',
        ),
        migrations.AlterField(
            model_name='theme',
            name='defaulttheme',
            field=models.BooleanField(verbose_name='Set Default Theme '),
        ),
        migrations.AlterField(
            model_name='theme',
            name='label',
            field=models.CharField(db_index=True, help_text='A short text describing the theme.', max_length=128, unique=True, verbose_name='Label'),
        ),
    ]
