# Generated by Django 2.2.24 on 2022-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appearance', '0025_auto_20220317_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='defaulttheme',
            field=models.BooleanField(verbose_name='Use to default Theme '),
        ),
    ]
